apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.database.password }}"
  JWT_SECRET: "myjwtsecretkey123"
  POSTGRES_PASSWORD: "{{ .Values.database.password }}"